[camera]
position = [0.0, 1.0, 6.8]
look_at = [0.0, 1.0, 0.0]
ref_up = [0.0, 1.0, 0.0]
fov = 19.5
focal_length = 1.0

[film]
resolution = [512, 512]
denoise = false
num_samples = 512

[integrator]
type = 'path'

# The maximum number of interactions in the scene to consider, e.g., when
# `max_depth=1`, only direct `Le` is considered.
max_depth = 32

# The depth that the integrator might start terminating the path by
# Russianroulette. If set to `1`, `bounces>1` will be considered to be
# terminated.
rr_depth = 8

# The probability in each depth to terminate the path by Russian roulette.
# The path do have a expected length of `rr_depth + 1 / rr_prob`.
rr_prob = 0.1

[[bsdf]]
type = 'diffuse'
name = 'grey'
R = [0.725, 0.71, 0.68] # rgb in [0, 1]^3 of color

[[bsdf]]
type = 'diffuse'
name = 'green'
R = [0.14, 0.45, 0.091]

[[bsdf]]
type = 'diffuse'
name = 'red'
R = [0.63, 0.065, 0.05]


[[primitive]]
type = 'trimesh'
path = 'geometry/light.stl'
face_normals = true
light = { type = 'area', emission = [17.0, 12.0, 5.0] }

[[primitive]]
type = 'trimesh'
path = 'geometry/floor.stl'
face_normals = true
bsdf = 'grey'

[[primitive]]
type = 'trimesh'
path = 'geometry/left.stl'
face_normals = true
bsdf = 'red'

[[primitive]]
type = 'trimesh'
path = 'geometry/right.stl'
face_normals = true
bsdf = 'green'

[[primitive]]
type = 'trimesh'
path = 'geometry/ceiling.stl'
face_normals = true
bsdf = 'grey'

[[primitive]]
type = 'trimesh'
path = 'geometry/back.stl'
face_normals = true
bsdf = 'grey'

[[primitive]]
type = 'trimesh'
path = 'geometry/boxes.stl'
face_normals = true
bsdf = 'grey'

