[camera]
position = [0.0, 0.05, 4.2]
look_at = [0.0, 0.0, 0.0]
ref_up = [0.0, 1.0, 0.0]
fov = 28
focal_length = 1.0

[film]
resolution = [768, 768]
denoise = false
num_samples = 512

[integrator]
type = 'path'
max_depth = 16
rr_depth = 6
rr_prob = 0.1
shader_reorder = false

[sampler]
type = 'independent'

[envmap]
texture = { type = 'constant', color = [0.015, 0.015, 0.018] }

[[bsdf]]
type = 'diffuse'
name = 'matte_white'
R = [0.78, 0.78, 0.78]

[[bsdf]]
type = 'diffuse'
name = 'black'
R = [0.0, 0.0, 0.0]

[[primitive]]
type = 'sphere'
center = [-2.6, 2.0, 2.6]
radius = 0.25
bsdf = 'black'
light = { type = 'area', emission = [140.0, 130.0, 115.0] }

[[primitive]]
type = 'trimesh'
path = 'geometry/low_div_sphere.ply'
bsdf = 'matte_white'
face_normals = false

