[camera]
position = [0.0, 0.2, 0.8]
look_at = [0, 0.17, 0]
ref_up = [0, 1, 0]
fov = 31.25
focal_length = 1.0

[film]
resolution = [800, 1000]
denoise = false
num_samples = 512

[integrator]
type = 'path'

max_depth = 32
rr_depth = 3
rr_prob = 0.1

shader_reorder = true

[[bsdf]]
type = "roughmetallic"
name = "metal"
rough = 0.03
R = [1.0, 1.0, 1.0]
etaI = [1.0, 1.0, 1.0]
etaT = [0.27105, 0.67693, 1.31640]
k = [3.60920, 2.62480, 2.29210]

[[bsdf]]
type = "smoothglass"
name = "glass"
R = [1, 1, 1]
T = [1, 1, 1]
etaI = 1.0
etaT = 1.5

[[bsdf]]
type = "smoothplastic"
name = "floor"
etaI = 1.0
etaT = 1.5
Rd = [0.578596, 0.578596, 0.578596]
Rs = [1, 1, 1]


[[bsdf]]
type = "smoothplastic"
name = "Plastic_Orange"
etaI = 1.0
etaT = 1.5
Rd = [1, 0.378676, 0.0134734]
Rs = [1, 1, 1]

[[bsdf]]
type = "roughplastic"
name = "Plastic_Black"
rough = 0.3
etaI = 1.0
etaT = 1.5
Rd = [0.00631, 0.00631, 0.00631]
Rs = [1, 1, 1]

[[primitive]]
type = "trimesh"
path = "geometry/Mesh013.obj"
bsdf = "Plastic_Black"

[[primitive]]
type = "trimesh"
path = "geometry/Mesh008.obj"
bsdf = "Plastic_Black"

[[primitive]]
type = "trimesh"
path = "geometry/Mesh010.obj"
bsdf = "glass"

[[primitive]]
type = "trimesh"
path = "geometry/Mesh009.obj"
bsdf = "Plastic_Orange"

[[primitive]]
type = "trimesh"
path = "geometry/Mesh015.obj"
bsdf = "metal"

[[primitive]]
type = "trimesh"
path = "geometry/Mesh012.obj"
bsdf = "Plastic_Orange"

[[primitive]]
type = "trimesh"
path = "geometry/Mesh016.obj"
bsdf = "Plastic_Orange"

[[primitive]]
type = "trimesh"
path = "geometry/Mesh017.obj"
bsdf = "Plastic_Black"

[[primitive]]
type = "trimesh"
path = "geometry/Mesh018.obj"
bsdf = "Plastic_Black"

[[primitive]]
type = "trimesh"
path = "geometry/Mesh019.obj"
bsdf = "Plastic_Black"

[[primitive]]
type = "trimesh"
path = "geometry/Mesh007.obj"
bsdf = "Plastic_Black"

[[primitive]]
type = "trimesh"
path = "geometry/Mesh006.obj"
bsdf = "Plastic_Orange"

[[primitive]]
type = "trimesh"
path = "geometry/Mesh005.obj"
bsdf = "Plastic_Black"

[[primitive]]
type = "trimesh"
path = "geometry/Mesh003.obj"
bsdf = "Plastic_Black"

[[primitive]]
type = "trimesh"
path = "geometry/Mesh002.obj"
bsdf = "metal"

[[primitive]]
type = "trimesh"
path = "geometry/Mesh001.obj"
bsdf = "Plastic_Orange"

[[primitive]]
type = "trimesh"
path = "geometry/Mesh011.obj"
bsdf = "Plastic_Black"

[[primitive]]
type = "trimesh"
path = "geometry/Mesh000.obj"
bsdf = "Plastic_Orange"

[[primitive]]
type = "trimesh"
path = "geometry/Mesh014.obj"
bsdf = "Plastic_Black"

[[primitive]]
type = "trimesh"
path = "geometry/Mesh004.obj"
bsdf = "floor"

[[primitive]]
type = "trimesh"
face_normals = true
path = "geometry/rectangle1.obj"
light = { type = 'area', emission = [2, 2, 2] }

[[primitive]]
type = "trimesh"
face_normals = true
path = "geometry/rectangle2.obj"
light = { type = 'area', emission = [2, 2, 2] }

[[primitive]]
type = "trimesh"
face_normals = true
path = "geometry/rectangle3.obj"
light = { type = 'area', emission = [2, 2, 2] }
