[camera]
position = [0.0, 1.0, 6.8]
look_at = [0.0, 1.0, 0.0]
ref_up = [0.0, 1.0, 0.0]
fov = 60
focal_length = 1.0

[film]
resolution = [512, 512]
denoise = false
num_samples = 1024

[integrator]
type = 'path'
max_depth = 32
rr_depth = 8
rr_prob = 0.1

[envmap]
[envmap.texture]
type = 'image'
path = 'texture/medieval_cafe_2k.exr'

[[bsdf]]
type = 'diffuse'
name = 'white'
R = [1.0, 1.0, 1.0]

[[primitive]]
type = 'sphere'
center = [0.0, 1.0, 0.0]
radius = 3.0
bsdf = 'white'
