[camera]
position = [15.0, -16.0, 25.8]
look_at = [0.0, 0.0, 0.0]
ref_up = [0.0, 1.0, 0.0]
fov = 13
focal_length = 1.0

[film]
resolution = [2560, 1440]
denoise = true
num_samples = 2048
clamp_at = 64.0

[integrator]
type = 'path'

max_depth = 512
rr_depth = 32
rr_prob = 0.1

[envmap]
scale = 6.0
rotation = [0.0, 0.0, 0.0]
texture = { type = 'image', path = 'texture/sky.exr' }

[[bsdf]]
type = 'diffuse'
name = 'grey'
R = [0.725, 0.71, 0.68]

[[bsdf]]
type = 'diffuse'
name = 'green'
R = [0.14, 0.45, 0.091]

[[bsdf]]
type = 'diffuse'
name = 'red'
R = [0.63, 0.065, 0.05]

[[bsdf]]
type = 'diffuse'
name = 'wireframe'

[bsdf.R]
type = 'wireframe'
line_width = 0.003
interior_color = [1.0, 1.0, 1.0]
edge_color = [0.2, 0.2, 0.2]

[[bsdf]]
type = 'glass'
name = 'glass-bk7'
R = [1.0, 1.0, 1.0]
T = [1.0, 1.0, 1.0]
etaI = 1.0
etaT = 1.51

[[primitive]]
type = 'trimesh'
path = 'geometry/transparent.ply'
bsdf = 'glass-bk7'
