# ShaderBall: No material (default)

[scene]
type = "usd"
path = "./shaderball_none.usda"
camera = "/standard_shader_ball_scene/camera"

[film]
resolution = [1024, 1024]
num_samples = 256
denoise = true

[integrator]
type = "path"
max_depth = 16
rr_depth = 4
