[camera]
position = [0.0, 1.0, 6.8]
look_at = [0.0, 1.0, 0.0]
ref_up = [0.0, 1.0, 0.0]
fov = 19.5
focal_length = 1.0

[film]
resolution = [1024, 1024]
denoise = false
num_samples = 1024

[integrator]
type = 'path'

max_depth = 32
rr_depth = 8
rr_prob = 0.1

[envmap]
texture = { type = 'constant', color = [1.0, 1.0, 1.0] }

[[bsdf]]
type = 'diffuse'
name = 'white'
R = [1.0, 1.0, 1.0]

[[primitive]]
type = 'sphere'
center = [0.0, 1.0, 0.0]
radius = 2.0
bsdf = 'white'

